import { sanitizeData } from "./model.js";

export const TUTORIAL_STEPS = [
  {
    tab: "property",
    title: "Property setup",
    summary: "Review the sample Maple Street Home profile, then edit the property details and notes.",
  },
  {
    tab: "projects",
    title: "Projects",
    summary: "Compare planned, active, and completed projects, then add or edit a project.",
  },
  {
    tab: "expenses",
    title: "Expenses",
    summary: "Classify sample costs, connect them to projects, and review documentation statuses.",
  },
  {
    tab: "documents",
    title: "Documents",
    summary: "Open the checklist, add sample document records, and simulate attaching a receipt or permit.",
  },
  {
    tab: "export",
    title: "CPA review and export",
    summary: "Preview the CPA review summary, download the sample CSV, and create a tutorial backup.",
  },
  {
    tab: "export",
    title: "Backup and restore",
    summary: "Use reset or restore inside the tutorial workspace to see how record recovery works.",
  },
];

export function createTutorialData() {
  return sanitizeData({
    properties: [
      {
        id: "tutorial_property_maple",
        name: "Maple Street Home",
        address: "123 Maple Street, Portland, OR 97201",
        purchaseDate: "2019-06-14",
        purchasePrice: 542000,
        notes: "Sample property for learning the workflow. Replace this with your real home only in the normal workspace.",
      },
    ],
    projects: [
      {
        id: "tutorial_project_kitchen",
        propertyId: "tutorial_property_maple",
        name: "Kitchen remodel",
        category: "kitchen",
        startDate: "2023-01-10",
        completionDate: "2023-06-21",
        contractor: "Northwest Builders LLC",
        permitNumber: "PR-2023-0418",
        status: "completed",
        scopeSummary: "Full kitchen refresh with cabinets, counters, backsplash tile, lighting, and appliance installation.",
        notes: "Cabinets, counters, tile, lighting, and appliance installation.",
      },
      {
        id: "tutorial_project_roof",
        propertyId: "tutorial_property_maple",
        name: "Roof replacement",
        category: "roof",
        startDate: "2022-09-05",
        completionDate: "2022-09-12",
        contractor: "Evergreen Roofing Co.",
        permitNumber: "",
        status: "completed",
        scopeSummary: "Full tear-off and replacement of the existing roof system.",
        notes: "Full tear-off and replacement. Good example of a large project to review with a CPA.",
      },
      {
        id: "tutorial_project_bath",
        propertyId: "tutorial_property_maple",
        name: "Bathroom addition",
        category: "bathroom",
        startDate: "2024-04-02",
        completionDate: "",
        contractor: "Harbor Home Design",
        status: "in progress",
        permitNumber: "PR-2024-0933",
        scopeSummary: "Bathroom addition with framing, plumbing, electrical, fixtures, and finish work.",
        notes: "Use this active project to practice adding new expenses and follow-up documents.",
      },
      {
        id: "tutorial_project_windows",
        propertyId: "tutorial_property_maple",
        name: "Window warranty follow-up",
        category: "windows/doors",
        startDate: "2024-05-12",
        completionDate: "",
        contractor: "Cascade Window Service",
        permitNumber: "",
        status: "blocked",
        scopeSummary: "Waiting for warranty confirmation before scheduling replacement glass.",
        notes: "Blocked projects help keep follow-ups visible without mixing them into completed work.",
      },
    ],
    expenses: [
      {
        id: "tutorial_expense_cabinets",
        propertyId: "tutorial_property_maple",
        projectId: "tutorial_project_kitchen",
        date: "2023-02-15",
        vendor: "Portland Tile Co.",
        description: "Backsplash tile and installation",
        amount: 1248.32,
        classification: "potential basis addition",
        category: "kitchen",
        documentationStatus: "receipt attached",
        notes: "Sample cost record linked to a receipt record. Confirm treatment with a CPA.",
      },
      {
        id: "tutorial_expense_electric",
        propertyId: "tutorial_property_maple",
        projectId: "tutorial_project_kitchen",
        date: "2023-03-18",
        vendor: "Electra Electric",
        description: "Under-cabinet lighting",
        amount: 620,
        classification: "potential basis addition",
        category: "electrical",
        documentationStatus: "invoice attached",
        notes: "Use this to see how invoices appear in the document checklist.",
      },
      {
        id: "tutorial_expense_roof",
        propertyId: "tutorial_property_maple",
        projectId: "tutorial_project_roof",
        date: "2022-09-12",
        vendor: "Evergreen Roofing Co.",
        description: "Full roof replacement",
        amount: 18732.48,
        classification: "potential basis addition",
        category: "roof",
        documentationStatus: "needs follow-up",
        notes: "Example of a high-value project where complete documentation matters.",
      },
      {
        id: "tutorial_expense_service",
        propertyId: "tutorial_property_maple",
        projectId: "",
        date: "2024-01-22",
        vendor: "QuickFix Plumbing",
        description: "Kitchen sink leak service visit",
        amount: 185,
        classification: "repair or maintenance",
        category: "plumbing",
        documentationStatus: "no document yet",
        notes: "This sample shows a smaller repair/maintenance item for CPA review.",
      },
      {
        id: "tutorial_expense_permit",
        propertyId: "tutorial_property_maple",
        projectId: "tutorial_project_bath",
        date: "2024-04-09",
        vendor: "City of Portland",
        description: "Bathroom addition permit",
        amount: 455,
        classification: "unclear / ask CPA",
        category: "bathroom",
        documentationStatus: "needs follow-up",
        notes: "Use unclear when you want a professional to decide how to treat the cost.",
      },
    ],
    documents: [
      {
        id: "tutorial_document_tile_receipt",
        propertyId: "tutorial_property_maple",
        projectId: "tutorial_project_kitchen",
        expenseId: "tutorial_expense_cabinets",
        displayName: "Tile receipt",
        documentType: "receipt",
        addedDate: "2023-02-16",
        notes: "Tutorial document record only. No real file is stored.",
        ocrText: "Sample receipt text: Portland Tile Co. backsplash tile and installation.",
        hasFile: false,
        fileStatusNote: "Tutorial sample: attach a real file only in your normal workspace.",
      },
      {
        id: "tutorial_document_electric_invoice",
        propertyId: "tutorial_property_maple",
        projectId: "tutorial_project_kitchen",
        expenseId: "tutorial_expense_electric",
        displayName: "Lighting invoice",
        documentType: "invoice",
        addedDate: "2023-03-20",
        notes: "Use this sample to practice linking an invoice to an expense.",
        ocrText: "Sample invoice text: under-cabinet lighting, labor, and materials.",
        hasFile: false,
        fileStatusNote: "Tutorial sample: no file copy is stored.",
      },
      {
        id: "tutorial_document_bath_permit",
        propertyId: "tutorial_property_maple",
        projectId: "tutorial_project_bath",
        expenseId: "tutorial_expense_permit",
        displayName: "Bathroom permit note",
        documentType: "permit",
        addedDate: "2024-04-10",
        notes: "Permit records help keep municipal approvals near the related project.",
        ocrText: "",
        hasFile: false,
        fileStatusNote: "Tutorial sample: add a permit file in the normal workspace when you have one.",
      },
      {
        id: "tutorial_document_roof_payment",
        propertyId: "tutorial_property_maple",
        projectId: "tutorial_project_roof",
        expenseId: "tutorial_expense_roof",
        displayName: "Roof payment confirmation",
        documentType: "payment record",
        addedDate: "2022-09-13",
        notes: "Payment records can help reconcile invoices and receipts during review.",
        ocrText: "Sample payment confirmation for Evergreen Roofing Co.",
        hasFile: false,
        fileStatusNote: "Tutorial sample: no bank record file is stored.",
      },
      {
        id: "tutorial_document_window_warranty",
        propertyId: "tutorial_property_maple",
        projectId: "tutorial_project_windows",
        expenseId: "",
        displayName: "Window warranty email",
        documentType: "warranty",
        addedDate: "2024-05-15",
        notes: "Warranty records help separate repair follow-up from new improvement work.",
        ocrText: "Sample warranty text for window service follow-up.",
        hasFile: false,
        fileStatusNote: "Tutorial sample: add the real warranty file in your normal workspace.",
      },
      {
        id: "tutorial_document_kitchen_photo",
        propertyId: "tutorial_property_maple",
        projectId: "tutorial_project_kitchen",
        expenseId: "",
        displayName: "Kitchen before and after photos",
        documentType: "photo",
        addedDate: "2023-06-22",
        notes: "Photo records can help explain the scope of a project.",
        ocrText: "",
        hasFile: false,
        fileStatusNote: "Tutorial sample: no photo file is stored.",
      },
    ],
  });
}
