import { sanitizeData } from "./model.js";

const MAPLE_PROPERTY_ID = "tutorial_property_maple";
const CEDAR_PROPERTY_ID = "tutorial_property_cedar";

export const TUTORIAL_STEPS = [
  {
    tab: "property",
    title: "Add a property",
    summary: "Review the sample home profile and see where core property details belong.",
  },
  {
    tab: "projects",
    title: "Add an improvement project",
    summary: "Open a project file, review dates, contractor details, permits, and supporting files.",
  },
  {
    tab: "expenses",
    title: "Record expenses",
    summary: "Connect sample costs to a property or project and review receipt/document status.",
  },
  {
    tab: "documents",
    title: "Attach documents",
    summary: "Add sample receipts, invoices, permits, photos, contracts, and notes to the document library.",
  },
  {
    tab: "export",
    title: "Export summaries",
    summary: "Preview a review packet and download a spreadsheet-friendly expense export.",
  },
  {
    tab: "export",
    title: "Back up your home file",
    summary: "Create or restore a sample backup without touching your real binder.",
  },
];

export function createTutorialData() {
  return sanitizeData({
    properties: [
      {
        id: MAPLE_PROPERTY_ID,
        name: "Maple Street Home",
        address: "123 Maple Street, Portland, OR 97201",
        purchaseDate: "2019-06-14",
        purchasePrice: 542000,
        notes: "Sample property for learning the workflow. Replace this with your real home only in the normal workspace.",
      },
      {
        id: CEDAR_PROPERTY_ID,
        name: "Cedar Lane Cottage",
        address: "48 Cedar Lane, Bend, OR 97702",
        purchaseDate: "2021-08-03",
        purchasePrice: 418500,
        notes: "Second sample property for testing property filters, exports, and details across more than one home.",
      },
    ],
    projects: [
      {
        id: "tutorial_project_kitchen",
        propertyId: MAPLE_PROPERTY_ID,
        name: "Kitchen remodel",
        category: "kitchen",
        startDate: "2023-01-10",
        completionDate: "2023-06-21",
        contractor: "Northwest Builders LLC",
        permitNumber: "PR-2023-0418",
        status: "completed",
        scopeSummary: "Full kitchen refresh with cabinets, counters, backsplash tile, lighting, and appliance installation.",
        notes: "Cabinets, counters, tile, lighting, and appliance installation.",
      },
      {
        id: "tutorial_project_roof",
        propertyId: MAPLE_PROPERTY_ID,
        name: "Roof replacement",
        category: "roof",
        startDate: "2022-09-05",
        completionDate: "2022-09-12",
        contractor: "Evergreen Roofing Co.",
        permitNumber: "",
        status: "completed",
        scopeSummary: "Full tear-off and replacement of the existing roof system.",
        notes: "Full tear-off and replacement. Good example of a large project to review later.",
      },
      {
        id: "tutorial_project_bath",
        propertyId: MAPLE_PROPERTY_ID,
        name: "Bathroom addition",
        category: "bathroom",
        startDate: "2024-04-02",
        completionDate: "",
        contractor: "Harbor Home Design",
        status: "in progress",
        permitNumber: "PR-2024-0933",
        scopeSummary: "Bathroom addition with framing, plumbing, electrical, fixtures, and finish work.",
        notes: "Use this active project to practice adding new expenses and follow-up documents.",
      },
      {
        id: "tutorial_project_windows",
        propertyId: MAPLE_PROPERTY_ID,
        name: "Window warranty follow-up",
        category: "windows/doors",
        startDate: "2024-05-12",
        completionDate: "",
        contractor: "Cascade Window Service",
        permitNumber: "",
        status: "blocked",
        scopeSummary: "Waiting for warranty confirmation before scheduling replacement glass.",
        notes: "Blocked projects help keep follow-ups visible without mixing them into completed work.",
      },
      {
        id: "tutorial_project_interior_paint",
        propertyId: MAPLE_PROPERTY_ID,
        name: "Interior painting refresh",
        category: "interior painting",
        startDate: "2023-10-02",
        completionDate: "2023-10-06",
        contractor: "Rose City Painting",
        permitNumber: "",
        status: "completed",
        scopeSummary: "Repainted entry, stairwell, hallway, living room, and primary bedroom with wall repairs before finish coats.",
        notes: "Useful for testing a project with photos, paint receipts, and contractor invoices.",
      },
      {
        id: "tutorial_project_exterior_paint",
        propertyId: MAPLE_PROPERTY_ID,
        name: "Exterior painting and trim repair",
        category: "exterior painting",
        startDate: "2024-07-08",
        completionDate: "2024-07-19",
        contractor: "Summit Exterior Co.",
        permitNumber: "",
        status: "completed",
        scopeSummary: "Pressure wash, scrape, prime, repair trim boards, and repaint siding, porch columns, and fascia.",
        notes: "Shows how exterior work can combine painting, trim, and photo documentation.",
      },
      {
        id: "tutorial_project_water_heater",
        propertyId: MAPLE_PROPERTY_ID,
        name: "Water heater replacement",
        category: "water heater",
        startDate: "2024-02-12",
        completionDate: "2024-02-12",
        contractor: "QuickFix Plumbing",
        permitNumber: "WH-2024-1182",
        status: "completed",
        scopeSummary: "Replaced failed tank water heater with a high-efficiency unit and updated shutoff hardware.",
        notes: "Includes a permit, invoice, warranty, and payment proof for a small but complete project file.",
      },
      {
        id: "tutorial_project_basement_drainage",
        propertyId: MAPLE_PROPERTY_ID,
        name: "Basement drainage correction",
        category: "drainage/grading",
        startDate: "2024-09-03",
        completionDate: "",
        contractor: "GroundWorks Northwest",
        permitNumber: "",
        status: "in progress",
        scopeSummary: "French drain, downspout extensions, grading correction, and moisture monitoring around the basement wall.",
        notes: "Active project for testing open follow-ups, estimates, inspection notes, and partial expenses.",
      },
      {
        id: "tutorial_project_deck",
        propertyId: MAPLE_PROPERTY_ID,
        name: "Deck boards and railing upgrade",
        category: "deck/patio/porch",
        startDate: "2024-08-05",
        completionDate: "",
        contractor: "Backyard Build Co.",
        permitNumber: "PR-2024-1840",
        status: "planned",
        scopeSummary: "Replace aging deck boards, update railing sections, and add stair lighting after permit approval.",
        notes: "Planned project with an estimate and permit but no final invoice yet.",
      },
      {
        id: "tutorial_project_attic",
        propertyId: MAPLE_PROPERTY_ID,
        name: "Attic insulation upgrade",
        category: "insulation/weatherization",
        startDate: "2023-11-13",
        completionDate: "2023-11-14",
        contractor: "EcoLayer Insulation",
        permitNumber: "",
        status: "completed",
        scopeSummary: "Air sealed attic penetrations and added blown-in insulation to improve comfort and efficiency.",
        notes: "Includes before photos, invoice, and warranty-style work summary.",
      },
      {
        id: "tutorial_project_driveway",
        propertyId: MAPLE_PROPERTY_ID,
        name: "Driveway resurfacing",
        category: "driveway/walkway",
        startDate: "2025-04-21",
        completionDate: "",
        contractor: "Pioneer Paving",
        permitNumber: "",
        status: "planned",
        scopeSummary: "Patch cracks, level low areas, resurface driveway, and reseal walkway approach.",
        notes: "Future work sample with estimate and planning documents.",
      },
      {
        id: "tutorial_project_cedar_flooring",
        propertyId: CEDAR_PROPERTY_ID,
        name: "Cottage flooring replacement",
        category: "flooring",
        startDate: "2022-05-16",
        completionDate: "2022-05-24",
        contractor: "High Desert Floors",
        permitNumber: "",
        status: "completed",
        scopeSummary: "Removed damaged carpet and installed engineered hardwood in the living room, hall, and bedrooms.",
        notes: "Second-property sample for testing filters, exports, and property summaries.",
      },
      {
        id: "tutorial_project_cedar_hvac",
        propertyId: CEDAR_PROPERTY_ID,
        name: "Mini-split heat pump install",
        category: "HVAC",
        startDate: "2023-03-07",
        completionDate: "2023-03-09",
        contractor: "Cascade Comfort Systems",
        permitNumber: "MECH-2023-2204",
        status: "completed",
        scopeSummary: "Installed two-zone ductless heat pump system with exterior condenser and wall-mounted heads.",
        notes: "Shows mechanical permits, equipment warranty, and contractor invoices.",
      },
      {
        id: "tutorial_project_cedar_landscape",
        propertyId: CEDAR_PROPERTY_ID,
        name: "Front yard drainage and landscaping",
        category: "landscaping",
        startDate: "2024-04-15",
        completionDate: "",
        contractor: "Juniper Yardworks",
        permitNumber: "",
        status: "in progress",
        scopeSummary: "Regrade front yard, install dry creek bed, replace shrubs, and add drip irrigation zones.",
        notes: "Useful for testing outdoor project details and several document types.",
      },
    ],
    expenses: [
      {
        id: "tutorial_expense_cabinets",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_kitchen",
        date: "2023-02-15",
        vendor: "Portland Tile Co.",
        description: "Backsplash tile and installation",
        amount: 1248.32,
        classification: "potential basis addition",
        category: "kitchen",
        documentationStatus: "receipt attached",
        notes: "Sample cost linked to a receipt. Cost type can be reviewed later.",
      },
      {
        id: "tutorial_expense_electric",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_kitchen",
        date: "2023-03-18",
        vendor: "Electra Electric",
        description: "Under-cabinet lighting",
        amount: 620,
        classification: "potential basis addition",
        category: "electrical",
        documentationStatus: "invoice attached",
        notes: "Use this to see how invoices appear in the document checklist.",
      },
      {
        id: "tutorial_expense_roof",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_roof",
        date: "2022-09-12",
        vendor: "Evergreen Roofing Co.",
        description: "Full roof replacement",
        amount: 18732.48,
        classification: "potential basis addition",
        category: "roof",
        documentationStatus: "needs follow-up",
        notes: "Example of a high-value project where complete documentation matters.",
      },
      {
        id: "tutorial_expense_service",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "",
        date: "2024-01-22",
        vendor: "QuickFix Plumbing",
        description: "Kitchen sink leak service visit",
        amount: 185,
        classification: "repair or maintenance",
        category: "plumbing",
        documentationStatus: "no document yet",
        notes: "This sample shows a smaller repair / upkeep item for later review.",
      },
      {
        id: "tutorial_expense_permit",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_bath",
        date: "2024-04-09",
        vendor: "City of Portland",
        description: "Bathroom addition permit",
        amount: 455,
        classification: "unclear / ask CPA",
        category: "bathroom",
        documentationStatus: "needs follow-up",
        notes: "Use Not sure, review later when you want to revisit the cost type.",
      },
      {
        id: "tutorial_expense_countertops",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_kitchen",
        date: "2023-04-07",
        vendor: "Willamette Stoneworks",
        description: "Quartz countertop fabrication and install",
        amount: 4850,
        classification: "potential basis addition",
        category: "kitchen",
        documentationStatus: "invoice attached",
        notes: "Countertop invoice linked to the completed kitchen remodel.",
      },
      {
        id: "tutorial_expense_appliances",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_kitchen",
        date: "2023-05-11",
        vendor: "Northwest Appliance Outlet",
        description: "Range and dishwasher package",
        amount: 2749.98,
        classification: "unclear / ask CPA",
        category: "appliances",
        documentationStatus: "receipt attached",
        notes: "Sample appliance purchase marked Not sure, review later.",
      },
      {
        id: "tutorial_expense_bath_framing",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_bath",
        date: "2024-04-18",
        vendor: "Harbor Home Design",
        description: "Bathroom addition framing deposit",
        amount: 6200,
        classification: "potential basis addition",
        category: "addition/structural",
        documentationStatus: "invoice attached",
        notes: "Deposit expense for an active project with follow-up items still open.",
      },
      {
        id: "tutorial_expense_bath_fixtures",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_bath",
        date: "2024-05-03",
        vendor: "River Supply Co.",
        description: "Vanity, sink, faucet, and bath fixtures",
        amount: 1895.66,
        classification: "potential basis addition",
        category: "bathroom",
        documentationStatus: "receipt attached",
        notes: "Material receipt linked to the bathroom addition.",
      },
      {
        id: "tutorial_expense_window_inspection",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_windows",
        date: "2024-05-12",
        vendor: "Cascade Window Service",
        description: "Warranty inspection visit",
        amount: 95,
        classification: "repair or maintenance",
        category: "windows/doors",
        documentationStatus: "invoice attached",
        notes: "Small service visit tied to a blocked warranty follow-up.",
      },
      {
        id: "tutorial_expense_interior_paint_labor",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_interior_paint",
        date: "2023-10-06",
        vendor: "Rose City Painting",
        description: "Interior prep, patching, and paint labor",
        amount: 3360,
        classification: "repair or maintenance",
        category: "interior painting",
        documentationStatus: "invoice attached",
        notes: "Interior painting sample for comparing repair and improvement cost types.",
      },
      {
        id: "tutorial_expense_interior_paint_materials",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_interior_paint",
        date: "2023-09-29",
        vendor: "Paint & Paper Supply",
        description: "Primer, wall paint, trim paint, and patch materials",
        amount: 416.72,
        classification: "repair or maintenance",
        category: "interior painting",
        documentationStatus: "receipt attached",
        notes: "Material receipt attached to a completed interior project.",
      },
      {
        id: "tutorial_expense_exterior_paint_labor",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_exterior_paint",
        date: "2024-07-19",
        vendor: "Summit Exterior Co.",
        description: "Exterior painting and trim repair labor",
        amount: 7200,
        classification: "unclear / ask CPA",
        category: "exterior painting",
        documentationStatus: "invoice attached",
        notes: "Exterior project with mixed painting and trim repair details.",
      },
      {
        id: "tutorial_expense_exterior_trim",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_exterior_paint",
        date: "2024-07-11",
        vendor: "Bridgetown Lumber",
        description: "Fascia and porch trim replacement boards",
        amount: 832.41,
        classification: "potential basis addition",
        category: "trim/millwork",
        documentationStatus: "receipt attached",
        notes: "Shows a material cost linked to the same exterior project.",
      },
      {
        id: "tutorial_expense_water_heater",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_water_heater",
        date: "2024-02-12",
        vendor: "QuickFix Plumbing",
        description: "High-efficiency water heater replacement",
        amount: 2410,
        classification: "unclear / ask CPA",
        category: "water heater",
        documentationStatus: "invoice attached",
        notes: "Complete small project with invoice, permit, and warranty files.",
      },
      {
        id: "tutorial_expense_water_heater_permit",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_water_heater",
        date: "2024-02-13",
        vendor: "City of Portland",
        description: "Water heater permit",
        amount: 128,
        classification: "unclear / ask CPA",
        category: "permits/fees",
        documentationStatus: "receipt attached",
        notes: "Permit fee linked to the water heater replacement.",
      },
      {
        id: "tutorial_expense_drainage_estimate",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_basement_drainage",
        date: "2024-08-28",
        vendor: "GroundWorks Northwest",
        description: "Drainage design and project deposit",
        amount: 1500,
        classification: "potential basis addition",
        category: "drainage/grading",
        documentationStatus: "invoice attached",
        notes: "Deposit on an active basement drainage project.",
      },
      {
        id: "tutorial_expense_downspouts",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_basement_drainage",
        date: "2024-09-05",
        vendor: "Gutter House",
        description: "Downspout extension materials",
        amount: 276.88,
        classification: "potential basis addition",
        category: "gutters/downspouts",
        documentationStatus: "receipt attached",
        notes: "Outdoor materials linked to an active drainage project.",
      },
      {
        id: "tutorial_expense_deck_estimate",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_deck",
        date: "2024-07-29",
        vendor: "Backyard Build Co.",
        description: "Deck replacement estimate deposit",
        amount: 500,
        classification: "unclear / ask CPA",
        category: "deck/patio/porch",
        documentationStatus: "needs follow-up",
        notes: "Planned project deposit without final project documentation yet.",
      },
      {
        id: "tutorial_expense_attic_insulation",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_attic",
        date: "2023-11-14",
        vendor: "EcoLayer Insulation",
        description: "Attic air sealing and blown-in insulation",
        amount: 3185,
        classification: "potential basis addition",
        category: "insulation/weatherization",
        documentationStatus: "invoice attached",
        notes: "Weatherization project with invoice and before/after photos.",
      },
      {
        id: "tutorial_expense_driveway_estimate",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_driveway",
        date: "2025-03-18",
        vendor: "Pioneer Paving",
        description: "Driveway resurfacing estimate",
        amount: 0,
        classification: "unclear / ask CPA",
        category: "driveway/walkway",
        documentationStatus: "no document yet",
        notes: "Zero-dollar planning item to show a future estimate that has not become an expense yet.",
      },
      {
        id: "tutorial_expense_cedar_flooring",
        propertyId: CEDAR_PROPERTY_ID,
        projectId: "tutorial_project_cedar_flooring",
        date: "2022-05-24",
        vendor: "High Desert Floors",
        description: "Engineered hardwood flooring and installation",
        amount: 6825.4,
        classification: "potential basis addition",
        category: "flooring",
        documentationStatus: "invoice attached",
        notes: "Second-property flooring project with invoice and photos.",
      },
      {
        id: "tutorial_expense_cedar_hvac",
        propertyId: CEDAR_PROPERTY_ID,
        projectId: "tutorial_project_cedar_hvac",
        date: "2023-03-09",
        vendor: "Cascade Comfort Systems",
        description: "Two-zone mini-split heat pump install",
        amount: 11240,
        classification: "potential basis addition",
        category: "HVAC",
        documentationStatus: "invoice attached",
        notes: "HVAC project with permit, warranty, and payment proof.",
      },
      {
        id: "tutorial_expense_cedar_hvac_permit",
        propertyId: CEDAR_PROPERTY_ID,
        projectId: "tutorial_project_cedar_hvac",
        date: "2023-03-10",
        vendor: "Deschutes County",
        description: "Mechanical permit fee",
        amount: 210,
        classification: "unclear / ask CPA",
        category: "permits/fees",
        documentationStatus: "receipt attached",
        notes: "Permit fee attached to a second-property HVAC project.",
      },
      {
        id: "tutorial_expense_cedar_landscape_design",
        propertyId: CEDAR_PROPERTY_ID,
        projectId: "tutorial_project_cedar_landscape",
        date: "2024-04-08",
        vendor: "Juniper Yardworks",
        description: "Drainage and planting plan",
        amount: 850,
        classification: "unclear / ask CPA",
        category: "plans/design",
        documentationStatus: "invoice attached",
        notes: "Design/planning expense for an outdoor project.",
      },
      {
        id: "tutorial_expense_cedar_irrigation",
        propertyId: CEDAR_PROPERTY_ID,
        projectId: "tutorial_project_cedar_landscape",
        date: "2024-04-22",
        vendor: "Juniper Yardworks",
        description: "Drip irrigation materials and installation",
        amount: 2195,
        classification: "potential basis addition",
        category: "irrigation",
        documentationStatus: "needs follow-up",
        notes: "Outdoor project expense that still needs a linked document.",
      },
    ],
    documents: [
      {
        id: "tutorial_document_tile_receipt",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_kitchen",
        expenseId: "tutorial_expense_cabinets",
        displayName: "Tile receipt",
        documentType: "receipt",
        addedDate: "2023-02-16",
        notes: "Tutorial document entry only. No real file is stored.",
        ocrText: "Sample receipt text: Portland Tile Co. backsplash tile and installation.",
        hasFile: false,
        fileStatusNote: "Tutorial sample: attach a real file only in your normal workspace.",
      },
      {
        id: "tutorial_document_electric_invoice",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_kitchen",
        expenseId: "tutorial_expense_electric",
        displayName: "Lighting invoice",
        documentType: "invoice",
        addedDate: "2023-03-20",
        notes: "Use this sample to practice linking an invoice to an expense.",
        ocrText: "Sample invoice text: under-cabinet lighting, labor, and materials.",
        hasFile: false,
        fileStatusNote: "Tutorial sample: no file copy is stored.",
      },
      {
        id: "tutorial_document_bath_permit",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_bath",
        expenseId: "tutorial_expense_permit",
        displayName: "Bathroom permit note",
        documentType: "permit",
        addedDate: "2024-04-10",
        notes: "Permit files help keep municipal approvals near the related project.",
        ocrText: "",
        hasFile: false,
        fileStatusNote: "Tutorial sample: add a permit file in the normal workspace when you have one.",
      },
      {
        id: "tutorial_document_roof_payment",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_roof",
        expenseId: "tutorial_expense_roof",
        displayName: "Roof payment confirmation",
        documentType: "payment record",
        addedDate: "2022-09-13",
        notes: "Payment proof can help reconcile invoices and receipts during review.",
        ocrText: "Sample payment confirmation for Evergreen Roofing Co.",
        hasFile: false,
        fileStatusNote: "Tutorial sample: no bank file is stored.",
      },
      {
        id: "tutorial_document_window_warranty",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_windows",
        expenseId: "",
        displayName: "Window warranty email",
        documentType: "warranty",
        addedDate: "2024-05-15",
        notes: "Warranty files help separate repair follow-up from new improvement work.",
        ocrText: "Sample warranty text for window service follow-up.",
        hasFile: false,
        fileStatusNote: "Tutorial sample: add the real warranty file in your normal workspace.",
      },
      {
        id: "tutorial_document_kitchen_photo",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_kitchen",
        expenseId: "",
        displayName: "Kitchen before and after photos",
        documentType: "photo",
        addedDate: "2023-06-22",
        notes: "Photos can help explain the scope of a project.",
        ocrText: "",
        hasFile: false,
        fileStatusNote: "Tutorial sample: no photo file is stored.",
      },
      {
        id: "tutorial_document_countertop_invoice",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_kitchen",
        expenseId: "tutorial_expense_countertops",
        displayName: "Countertop fabrication invoice",
        documentType: "invoice",
        addedDate: "2023-04-08",
        notes: "Sample countertop invoice linked to a kitchen expense.",
        ocrText: "Sample invoice text: quartz slabs, template visit, fabrication, delivery, and installation.",
        hasFile: false,
        fileStatusNote: "Tutorial sample: no file copy is stored.",
      },
      {
        id: "tutorial_document_appliance_receipt",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_kitchen",
        expenseId: "tutorial_expense_appliances",
        displayName: "Appliance package receipt",
        documentType: "receipt",
        addedDate: "2023-05-12",
        notes: "Receipt sample for an item marked Not sure, review later.",
        ocrText: "Sample receipt text: range, dishwasher, delivery, installation kit, and haul-away fee.",
        hasFile: false,
        fileStatusNote: "Tutorial sample: no appliance receipt file is stored.",
      },
      {
        id: "tutorial_document_bath_contract",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_bath",
        expenseId: "tutorial_expense_bath_framing",
        displayName: "Bathroom addition contract",
        documentType: "contract",
        addedDate: "2024-04-03",
        notes: "Contract sample for reviewing scope, deposit, and contractor information.",
        ocrText: "Sample contract text: framing, plumbing rough-in, electrical rough-in, inspections, fixtures, and finish work.",
        hasFile: false,
        fileStatusNote: "Tutorial sample: no contract file is stored.",
      },
      {
        id: "tutorial_document_bath_fixture_receipt",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_bath",
        expenseId: "tutorial_expense_bath_fixtures",
        displayName: "Bathroom fixture receipt",
        documentType: "receipt",
        addedDate: "2024-05-04",
        notes: "Material receipt linked to the active bathroom project.",
        ocrText: "Sample receipt text: vanity, sink, faucet, shower trim, and bath accessories.",
        hasFile: false,
        fileStatusNote: "Tutorial sample: no receipt file is stored.",
      },
      {
        id: "tutorial_document_interior_paint_invoice",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_interior_paint",
        expenseId: "tutorial_expense_interior_paint_labor",
        displayName: "Interior painting invoice",
        documentType: "invoice",
        addedDate: "2023-10-07",
        notes: "Invoice sample for completed interior work.",
        ocrText: "Sample invoice text: wall preparation, drywall patches, primer, two finish coats, and trim touch-ups.",
        hasFile: false,
        fileStatusNote: "Tutorial sample: no invoice file is stored.",
      },
      {
        id: "tutorial_document_interior_paint_receipt",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_interior_paint",
        expenseId: "tutorial_expense_interior_paint_materials",
        displayName: "Interior paint materials receipt",
        documentType: "receipt",
        addedDate: "2023-09-30",
        notes: "Receipt sample for paint and wall repair materials.",
        ocrText: "Sample receipt text: primer, eggshell wall paint, semi-gloss trim paint, rollers, trays, and patch compound.",
        hasFile: false,
        fileStatusNote: "Tutorial sample: no file copy is stored.",
      },
      {
        id: "tutorial_document_interior_paint_photos",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_interior_paint",
        expenseId: "",
        displayName: "Interior painting before and after photos",
        documentType: "photo",
        addedDate: "2023-10-07",
        notes: "Photo showing hallway patch repairs and final paint finish.",
        ocrText: "",
        hasFile: false,
        fileStatusNote: "Tutorial sample: no photo file is stored.",
      },
      {
        id: "tutorial_document_exterior_paint_invoice",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_exterior_paint",
        expenseId: "tutorial_expense_exterior_paint_labor",
        displayName: "Exterior painting invoice",
        documentType: "invoice",
        addedDate: "2024-07-20",
        notes: "Invoice sample for exterior repainting and trim repair.",
        ocrText: "Sample invoice text: pressure washing, scraping, priming, exterior paint, trim repair, and cleanup.",
        hasFile: false,
        fileStatusNote: "Tutorial sample: no invoice file is stored.",
      },
      {
        id: "tutorial_document_exterior_trim_receipt",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_exterior_paint",
        expenseId: "tutorial_expense_exterior_trim",
        displayName: "Exterior trim materials receipt",
        documentType: "receipt",
        addedDate: "2024-07-12",
        notes: "Material receipt linked to trim replacement work.",
        ocrText: "Sample receipt text: primed fascia boards, porch trim, fasteners, caulk, and flashing tape.",
        hasFile: false,
        fileStatusNote: "Tutorial sample: no file copy is stored.",
      },
      {
        id: "tutorial_document_exterior_before_after",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_exterior_paint",
        expenseId: "",
        displayName: "Exterior paint before and after photos",
        documentType: "photo",
        addedDate: "2024-07-20",
        notes: "Photo sample for documenting exterior project scope.",
        ocrText: "",
        hasFile: false,
        fileStatusNote: "Tutorial sample: no photo file is stored.",
      },
      {
        id: "tutorial_document_water_heater_invoice",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_water_heater",
        expenseId: "tutorial_expense_water_heater",
        displayName: "Water heater invoice",
        documentType: "invoice",
        addedDate: "2024-02-12",
        notes: "Invoice sample for equipment, labor, and haul-away.",
        ocrText: "Sample invoice text: high-efficiency water heater, expansion tank, shutoff valve, labor, and disposal.",
        hasFile: false,
        fileStatusNote: "Tutorial sample: no invoice file is stored.",
      },
      {
        id: "tutorial_document_water_heater_permit",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_water_heater",
        expenseId: "tutorial_expense_water_heater_permit",
        displayName: "Water heater permit receipt",
        documentType: "permit",
        addedDate: "2024-02-13",
        notes: "Permit linked to the water heater project.",
        ocrText: "Sample permit text: water heater replacement permit, permit number WH-2024-1182.",
        hasFile: false,
        fileStatusNote: "Tutorial sample: no permit file is stored.",
      },
      {
        id: "tutorial_document_water_heater_warranty",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_water_heater",
        expenseId: "",
        displayName: "Water heater warranty",
        documentType: "warranty",
        addedDate: "2024-02-14",
        notes: "Warranty sample for equipment model and coverage dates.",
        ocrText: "Sample warranty text: tank warranty, parts coverage, serial number, and installer information.",
        hasFile: false,
        fileStatusNote: "Tutorial sample: no warranty file is stored.",
      },
      {
        id: "tutorial_document_drainage_estimate",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_basement_drainage",
        expenseId: "tutorial_expense_drainage_estimate",
        displayName: "Basement drainage estimate",
        documentType: "contract",
        addedDate: "2024-08-29",
        notes: "Estimate sample for an active project that is not finished yet.",
        ocrText: "Sample estimate text: French drain, gravel, pipe, downspout tie-ins, grading, and moisture check.",
        hasFile: false,
        fileStatusNote: "Tutorial sample: no estimate file is stored.",
      },
      {
        id: "tutorial_document_downspout_receipt",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_basement_drainage",
        expenseId: "tutorial_expense_downspouts",
        displayName: "Downspout materials receipt",
        documentType: "receipt",
        addedDate: "2024-09-05",
        notes: "Receipt sample tied to the active basement drainage project.",
        ocrText: "Sample receipt text: corrugated pipe, adapters, splash blocks, and fittings.",
        hasFile: false,
        fileStatusNote: "Tutorial sample: no receipt file is stored.",
      },
      {
        id: "tutorial_document_drainage_photos",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_basement_drainage",
        expenseId: "",
        displayName: "Basement drainage progress photos",
        documentType: "photo",
        addedDate: "2024-09-06",
        notes: "Progress photo sample for an open project.",
        ocrText: "",
        hasFile: false,
        fileStatusNote: "Tutorial sample: no photo file is stored.",
      },
      {
        id: "tutorial_document_deck_estimate",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_deck",
        expenseId: "tutorial_expense_deck_estimate",
        displayName: "Deck railing estimate",
        documentType: "contract",
        addedDate: "2024-07-30",
        notes: "Estimate sample for planned deck work.",
        ocrText: "Sample estimate text: cedar deck boards, railing sections, stair lighting, labor, and permit coordination.",
        hasFile: false,
        fileStatusNote: "Tutorial sample: no estimate file is stored.",
      },
      {
        id: "tutorial_document_deck_permit",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_deck",
        expenseId: "",
        displayName: "Deck permit approval",
        documentType: "permit",
        addedDate: "2024-08-01",
        notes: "Permit sample for a planned exterior project.",
        ocrText: "Sample permit text: deck repair and railing update approved under PR-2024-1840.",
        hasFile: false,
        fileStatusNote: "Tutorial sample: no permit file is stored.",
      },
      {
        id: "tutorial_document_attic_invoice",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_attic",
        expenseId: "tutorial_expense_attic_insulation",
        displayName: "Attic insulation invoice",
        documentType: "invoice",
        addedDate: "2023-11-15",
        notes: "Invoice sample for weatherization work.",
        ocrText: "Sample invoice text: air sealing, blown-in insulation, baffles, prep, cleanup, and final depth report.",
        hasFile: false,
        fileStatusNote: "Tutorial sample: no invoice file is stored.",
      },
      {
        id: "tutorial_document_attic_photos",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_attic",
        expenseId: "",
        displayName: "Attic insulation before and after photos",
        documentType: "photo",
        addedDate: "2023-11-15",
        notes: "Photo sample for documenting weatherization work.",
        ocrText: "",
        hasFile: false,
        fileStatusNote: "Tutorial sample: no photo file is stored.",
      },
      {
        id: "tutorial_document_driveway_estimate",
        propertyId: MAPLE_PROPERTY_ID,
        projectId: "tutorial_project_driveway",
        expenseId: "tutorial_expense_driveway_estimate",
        displayName: "Driveway resurfacing estimate notes",
        documentType: "other",
        addedDate: "2025-03-19",
        notes: "Planning note sample for a future driveway project.",
        ocrText: "Sample estimate notes: crack repair, leveling, resurfacing, sealing, and walkway edge repair.",
        hasFile: false,
        fileStatusNote: "Tutorial sample: no estimate file is stored.",
      },
      {
        id: "tutorial_document_cedar_flooring_invoice",
        propertyId: CEDAR_PROPERTY_ID,
        projectId: "tutorial_project_cedar_flooring",
        expenseId: "tutorial_expense_cedar_flooring",
        displayName: "Cottage flooring invoice",
        documentType: "invoice",
        addedDate: "2022-05-25",
        notes: "Second-property invoice sample for flooring work.",
        ocrText: "Sample invoice text: carpet removal, engineered hardwood, underlayment, trim transitions, labor, and disposal.",
        hasFile: false,
        fileStatusNote: "Tutorial sample: no invoice file is stored.",
      },
      {
        id: "tutorial_document_cedar_flooring_photos",
        propertyId: CEDAR_PROPERTY_ID,
        projectId: "tutorial_project_cedar_flooring",
        expenseId: "",
        displayName: "Cottage flooring before and after photos",
        documentType: "photo",
        addedDate: "2022-05-25",
        notes: "Photo sample connected to a second-property project.",
        ocrText: "",
        hasFile: false,
        fileStatusNote: "Tutorial sample: no photo file is stored.",
      },
      {
        id: "tutorial_document_cedar_hvac_invoice",
        propertyId: CEDAR_PROPERTY_ID,
        projectId: "tutorial_project_cedar_hvac",
        expenseId: "tutorial_expense_cedar_hvac",
        displayName: "Mini-split installation invoice",
        documentType: "invoice",
        addedDate: "2023-03-10",
        notes: "HVAC invoice sample with equipment and labor details.",
        ocrText: "Sample invoice text: outdoor condenser, two indoor heads, refrigerant lines, electrical disconnect, and commissioning.",
        hasFile: false,
        fileStatusNote: "Tutorial sample: no invoice file is stored.",
      },
      {
        id: "tutorial_document_cedar_hvac_permit",
        propertyId: CEDAR_PROPERTY_ID,
        projectId: "tutorial_project_cedar_hvac",
        expenseId: "tutorial_expense_cedar_hvac_permit",
        displayName: "Mechanical permit receipt",
        documentType: "permit",
        addedDate: "2023-03-10",
        notes: "Permit sample for the cottage HVAC project.",
        ocrText: "Sample permit text: mechanical permit MECH-2023-2204 for ductless heat pump installation.",
        hasFile: false,
        fileStatusNote: "Tutorial sample: no permit file is stored.",
      },
      {
        id: "tutorial_document_cedar_hvac_warranty",
        propertyId: CEDAR_PROPERTY_ID,
        projectId: "tutorial_project_cedar_hvac",
        expenseId: "",
        displayName: "Mini-split equipment warranty",
        documentType: "warranty",
        addedDate: "2023-03-11",
        notes: "Warranty sample for equipment model, serial numbers, and service contact.",
        ocrText: "Sample warranty text: outdoor condenser serial number, indoor unit model numbers, parts coverage, and labor terms.",
        hasFile: false,
        fileStatusNote: "Tutorial sample: no warranty file is stored.",
      },
      {
        id: "tutorial_document_cedar_landscape_plan",
        propertyId: CEDAR_PROPERTY_ID,
        projectId: "tutorial_project_cedar_landscape",
        expenseId: "tutorial_expense_cedar_landscape_design",
        displayName: "Front yard drainage and planting plan",
        documentType: "plan or drawing",
        addedDate: "2024-04-09",
        notes: "Plan sample for an outdoor project that combines grading and planting areas.",
        ocrText: "Sample plan text: dry creek bed alignment, amended soil areas, drip irrigation zones, and native shrub locations.",
        hasFile: false,
        fileStatusNote: "Tutorial sample: no plan file is stored.",
      },
      {
        id: "tutorial_document_cedar_irrigation_note",
        propertyId: CEDAR_PROPERTY_ID,
        projectId: "tutorial_project_cedar_landscape",
        expenseId: "tutorial_expense_cedar_irrigation",
        displayName: "Irrigation installation note",
        documentType: "other",
        addedDate: "2024-04-23",
        notes: "Note sample for an expense that still needs final invoice documentation.",
        ocrText: "Sample note text: drip zones installed along front bed, side yard shrubs, and dry creek edge.",
        hasFile: false,
        fileStatusNote: "Tutorial sample: add the final invoice in the normal workspace when available.",
      },
    ],
  });
}
